### ISSUE TITLE
Cannot start acserver 

### ISSUE THREAD

**Issue by gitwikta** [schmic/ac-monitor#12]
Hi, finally I started ac-monitor and I can login and see admin page.
Currently, I do not know how to continue.
Everytimes I try to start server using ac-monitor I got (using ACDriver preset) :

..
checking server with preset ACDriver
Started server CZ Practice Server - please race and test PID: 1651
admin.server.start { name: 'ACDriver',
  reload: true,
  valid: true,
  msg: 'Preset ACDriver started' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

I am running Ubuntu 14 server. I got this kind of error for release and dev version of ac-monitor.
I would appreciate some hint :) Thank you

**Comment by schmic** [comment]
@gitwikta Is the path to your AC-Server-Directory correct? Please check that in 'config/default.json'.

Are you running on Windows or Linux?

**Comment by gitwikta** [comment]
good hint ! I am running Linux. It works now when I use exact path. Relative path did not work for me. Maybe I should add dot at the end ? "../." With full path it works. I can start acserver from ac-monitor.
Big thanks !

**Comment by schmic** [comment]
@gitwikta You should be able to use relative paths as well though I haven't tested a while on Linux.

On our Windows machine we have set:

```
{
  "ac": {
    "path": "..\ac-server"
  }
}
```

You should be able to do the same but use slashes instead of backslashes.
The path should be relative to the acMonitor.js file.
