### ISSUE TITLE
Cannot start multiple instances of acserver

### ISSUE THREAD

**Issue by gitwikta** [schmic/ac-monitor#13]
Hi, I have one more question to your nice project.
I use master version and it is possible to start acserver thru that.
The problem I have now is when started second instance of acserver.
When started it says:
Watchdog	Preset Btest found dead (Btest is a preset name)
Can I somehow disable watchdog ? Or do you know where is the problem ? 
(UBUNTU 64bit)

**Comment by schmic** [comment]
@gitwikta We run multiple (3-4) servers at once, that is possible.

The watchdog checks if the servers dies in the background every x seconds, depending on your configuration. Your problem is not the watchdog but the dying server.
Check the logfiles of the server to see why it's dying.

**Comment by schmic** [comment]
@gitwikta If you pull the latest commits you can disable the watchdog by setting the interval to 0. Though you should check why your server is dying anyway ...

**Comment by gitwikta** [comment]
I am sorry and thank you for your patience. I cannot start more servers on same ports. Maybe I am tired :) I am glad it runs now and I can manage my server in easy way. I will wait for docu...since I am not js familiar.
