### ISSUE TITLE
Server refuses to start in linux

### ISSUE THREAD

**Issue by gobozgz** [schmic/ac-monitor#17]
In Linux, When I try to start the server I got this error:

:~/tmp/ac-monitor$ uname -a
Linux 2.6.32-042stab106.4 #1 SMP Fri Mar 27 15:19:28 MSK 2015 x86_64 GNU/Linux

~/tmp/ac-monitor$ node -v
v0.12.4

~/tmp/ac-monitor$ node ./acMonitor.js
Database Path: /home/ascor/tmp/ac-monitor/config/db
acMonitor running at http://37.187.44.199:8081
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

Thanks for you attention,
David

**Comment by gitwikta** [comment]
Hi David,
Is the port 8081 free on your server ? It seems to be some apache running. Try to stop this apache or change port to some free ... Greetings

**Comment by gobozgz** [comment]
Yes, I have tried using different ports, I've also tried using hostname and the server’s IP address unsuccessfully. By the way, thank you very much for your work and your time :)

David

**Comment by gitwikta** [comment]
Not my project, i have just a free time.. When I open the url you presented I got Apache/2.2.22 (Debian) Server at 37.187.44.199 Port 8081 :) are you sure the is no apache binded to 8081 port on your host ?

**Comment by gobozgz** [comment]
Ok, I'm just a giddy goat, I just changed the port in the config file related to AC server, not ac-monitor.

Now Im ready to enjoy some Asseto Corsa races with my friends. Thank you very much and apologize my for the nuisance

Greetings,
David
