### ISSUE TITLE
dead server prob

### ISSUE THREAD

**Issue by TannuT** [schmic/ac-monitor#4]
![acmon](https://cloud.githubusercontent.com/assets/10135650/5413978/a33ab39c-8223-11e4-8fac-fce9c79f0810.jpg)

**Comment by TannuT** [comment]
i got it to all work no without any errors but it not showing me drivers on server.

**Comment by schmic** [comment]
@TannuT Yes, the session-handling is currently incomplete. You can't see the actual drivers at the moment.
